services:
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: npm run start:dev gateway
    env_file:
      - ./apps/gateway/.env
    depends_on:
      - auth
    volumes:
      - .:/usr/src/nest-prisma-rabbitMQ
      - /usr/src/nest-prisma-rabbitMQ/node_modules
      - /usr/src/nest-prisma-rabbitmq/prisma
    ports:
      - 3000:3000

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    depends_on:
      - mysql
      - rabbitmq
    volumes:
      - .:/usr/src/nest-prisma-rabbitMQ
      - /usr/src/nest-prisma-rabbitMQ/node_modules
      - /usr/src/nest-prisma-rabbitmq/prisma
    ports:
      - 3001:3001

  mysql:
    image: mysql
    env_file:
      - .env
    ports:
      - '3306:3306'

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
